### ISSUE TITLE
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

### ISSUE THREAD

**Issue by murbano-forteg** [fedecalendino/slack-release-notifier#1]
Hello

I am currently getting this error when using the workflow:

```
Run fedecalendino/slack-release-notifier@v2.1.0
/usr/bin/docker run --name b2b550133d7db42904d40ad36cc74ec4d5b7f_55c951 --label 8b2b55 --workdir /github/workspace --rm -e "INPUT_SLACK_WEBHOOK_URL" -e "INPUT_PYPI_PROJECT_NAME" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/truebit-nextgen/truebit-nextgen":"/github/workspace" 8b2b55:0133d7db42904d40ad36cc74ec4d5b7f
Traceback (most recent call last):
  File "/app/main.py", line 93, in <module>
    main()
  File "/app/main.py", line 89, in main
    message.send(params.slack_webhook_url)
  File "/app/slackhooks/client.py", line 27, in send
    json=self.serialize(),
  File "/app/slackhooks/client.py", line 19, in serialize
    self.blocks,
  File "/app/slackhooks/client.py", line 18, in <lambda>
    lambda block: block.serialize(),
  File "/app/slackhooks/blocks/section.py", line 26, in serialize
    "accessory": self._accessory.serialize(),
  File "/app/slackhooks/blocks/accessory.py", line 30, in serialize
    "value": self.value,
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
```

**Comment by fedecalendino** [comment]
Hi!

I just published the version `v3.0.2` with some improvements, and this should also fix your issue: https://github.com/marketplace/actions/slack-release-notifier

If you were using the `pypi` stuff from the previous versions keep in mind that that slightly changed giving you more flexibility by accepting three new values for custom text, emoji and url for the button.

Check the README file for more info.

Cheers,
Fede!
